server:
  port: 8081

spring:
  application:
    name: auth-service

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

logging:
  level:
    root: INFO
    org.ataraxii.authwishlist: INFO