spring:
  datasource:
    url: postgresql://auth_db:5432/${AUTH_DB_NAME}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 15
      idle-timeout: 60000
      minimum-idle: 2
      initialization-fail-timeout: -1

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka